version: '3.8'

services:
  api:
    container_name: RSBD_BE
    build: 
      context: ./RSBD_BE
      dockerfile: Dockerfile
      args:
        ASPNETCORE_EXPOSE_PORT: ${API_PORT_INSIDE}
    ports:
      - "${API_PORT_OUTSIDE}:${API_PORT_INSIDE}"
    environment:
      # Databases
      # EU
      DB_EU_WRITE_CS: "Host=eu-db-write;Port=${DB_PORT_INSIDE};Database=${DB_NAME_MASTER};Username=${DB_USER};Password=${DB_PASSWORD}"
      DB_EU_READ_CS: "Host=eu-db-read;Port=${DB_PORT_INSIDE};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      # US
      DB_US_WRITE_CS: "Host=us-db-write;Port=${DB_PORT_INSIDE};Database=${DB_NAME_MASTER};Username=${DB_USER};Password=${DB_PASSWORD}"
      DB_US_READ_CS: "Host=us-db-read;Port=${DB_PORT_INSIDE};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      # AS
      DB_AS_WRITE_CS: "Host=as-db-write;Port=${DB_PORT_INSIDE};Database=${DB_NAME_MASTER};Username=${DB_USER};Password=${DB_PASSWORD}"
      DB_AS_READ_CS: "Host=as-db-read;Port=${DB_PORT_INSIDE};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      # Other
      ASPNETCORE_URLS: http://+:${API_PORT_INSIDE}
      MODE: Development
    networks:
      - backendNetwork

  # EU
  # WRITE
  eu-db-write:
    container_name: EU-DB-WRITE
    build: ./dbConfig/master
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_MASTER}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_SLAVE=eu-db-read
    ports:
        - "${DB_EU_WRITE_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'eu-db-write-v:/var/lib/postgresql/data'
  
  # READ
  eu-db-read:
    container_name: EU-DB-READ
    build: ./dbConfig/slave
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_DB_NAME=${DB_NAME_MASTER}
      - PG_REP_MASTER=eu-db-write
    ports:
        - "${DB_EU_READ_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'eu-db-read-v:/var/lib/postgresql/data'  

  # US
  # WRITE
  us-db-write:
    container_name: US-DB-WRITE
    build: ./dbConfig/master
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_MASTER}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_SLAVE=us-db-read
    ports:
        - "${DB_US_WRITE_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'us-db-write-v:/var/lib/postgresql/data'

  # READ
  us-db-read:
    container_name: US-DB-READ
    build: ./dbConfig/slave
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_DB_NAME=${DB_NAME_MASTER}
      - PG_REP_MASTER=us-db-write
    ports:
        - "${DB_US_READ_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'us-db-read-v:/var/lib/postgresql/data'  

  # AS
  # WRITE
  as-db-write:
    container_name: AS-DB-WRITE
    build: ./dbConfig/master
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_MASTER}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_SLAVE=as-db-read
    ports:
        - "${DB_AS_WRITE_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'as-db-write-v:/var/lib/postgresql/data'
  
  # READ
  as-db-read:
    container_name: AS-DB-READ
    build: ./dbConfig/slave
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PG_REP_USER=${DB_USER}
      - PG_REP_PASSWORD=${DB_PASSWORD}
      - PG_REP_DB_NAME=${DB_NAME_MASTER}
      - PG_REP_MASTER=as-db-write
    ports:
        - "${DB_AS_READ_PORT_OUTSIDE}:${DB_PORT_INSIDE}"
    networks:
      - backendNetwork
    volumes: 
      - 'as-db-read-v:/var/lib/postgresql/data'  


volumes:
  eu-db-write-v:
  eu-db-read-v:
  us-db-write-v:
  us-db-read-v:
  as-db-write-v:
  as-db-read-v:

networks:
    backendNetwork: