apiVersion: v1
kind: Secret
metadata:
  name: rsbd-secret
type: Opaque
data:
  postgres-user: QWRhbURldg==
  postgres-password: QWRhbURldg==
  postgres-db-slave: UlNCRF9EQg==
  postgres-db-master: UlNCRF9EQl9N

