apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-read-deployment
  labels:
    app: us-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-read
  template:
    metadata:
      labels:
        app: us-read
        dude: "true"
    spec:
      containers:
      - name: us-read
        image: rsbd-us-read
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
          name: us-read
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-db-slave
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: us-read-volume
      volumes:
        - name: us-read-volume
          persistentVolumeClaim:
            claimName: us-read-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: us-read-service
spec:
  type: NodePort
  selector:
    app: us-read
  ports:
  - port: 5603
    targetPort: us-read
    nodePort: 30003
