apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-write-deployment
  labels:
    app: us-write
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-write
  template:
    metadata:
      labels:
        app: us-write
        dude: "true"
    spec:
      containers:
      - name: us-write
        image: rsbd-us-write
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
          name: us-write
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: rsbd-secret
              key: postgres-db-master
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: us-write-volume
      volumes:
        - name: us-write-volume
          persistentVolumeClaim:
            claimName: us-write-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: us-write-service
spec:
  type: NodePort
  selector:
    app: us-write
  ports:
  - port: 5604
    targetPort: us-write
    nodePort: 30004
            